name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print Message
        run: echo "Hello, GitHub Actions!"
        

    
