name: This is my first workflow

on: push

jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: welcome message
          run: echo "My first Github action job"

        - name: list files
          run: ls /var  
