name: This is my First Work flow

on: push
   
jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions!"

      - name: list files
        run: ls
      - name: last step
        run: echo "Today is " date  

