name: This is my First Work flow

on:
  push:
    branches:
      - main

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
       - name: Print Message
        run: echo "Hello, GitHub Actions!"
