name: This is my First Workflow

on: push

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions!"

      - name: List files
        run: ls /var
