name: Multi-OS CI Workflow

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on Multiple OS
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print System Information
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          uname -a || systeminfo
      
      - name: Run Sample Command
        run: echo "Hello from ${{ matrix.os }}"
